package me.itzkiba.pluginMST.listeners.spawnitem;

import me.itzkiba.pluginMST.helperfunctions.RandomNumber;

public class SuffixName {

    private static final String[] suffixArray =
            {
                    "of Power",
                    "of Might",
                    "of Fury",
                    "of Rage",
                    "of Strength",
                    "of Titans",
                    "of Gods",
                    "of the Elements",
                    "of Fire",
                    "of Frost",
                    "of Thunder",
                    "of the Wind",
                    "of the Earth",
                    "of the Ocean",
                    "of the Sky",
                    "of Storms",
                    "of Lightning",
                    "of the Sun",
                    "of the Moon",
                    "of Stars",
                    "of the Night",
                    "of Darkness",
                    "of Light",
                    "of Dawn",
                    "of Dusk",
                    "of Twilight",
                    "of the Void",
                    "of Chaos",
                    "of Destruction",
                    "of Desolation",
                    "of Devastation",
                    "of Annihilation",
                    "of the Apocalypse",
                    "of the End",
                    "of the Beginning",
                    "of the Future",
                    "of the Past",
                    "of History",
                    "of Legends",
                    "of Myths",
                    "of Fantasy",
                    "of Reality",
                    "of Dreams",
                    "of Nightmares",
                    "of Shadows",
                    "of Silence",
                    "of Sages",
                    "of the Oracle",
                    "of the Seer",
                    "of Visionaries",
                    "of Prophets",
                    "of Priests",
                    "of Paladins",
                    "of Knights",
                    "of Crusaders",
                    "of Warriors",
                    "of Gladiators",
                    "of Champions",
                    "of Heroes",
                    "of Legends",
                    "of Myths",
                    "of Reality",
                    "of Dreams",
                    "of Nightmares",
                    "of Shadows",
                    "of Light",
                    "of Spirits",
                    "of Souls",
                    "of Heart",
                    "of Courage",
                    "of Honor",
                    "of Duty",
                    "of Loyalty",
                    "of Faith",
                    "of Hope",
                    "of Joy",
                    "of Peace",
                    "of Prosperity",
                    "of Wealth",
                    "of Fortune",
                    "of Luck",
                    "of Destiny"
            };

    public static String get()
    {
        int index = RandomNumber.generateInt(0, suffixArray.length-1);
        return suffixArray[index];
    }
}
